### ISSUE TITLE
Combined feed

### ISSUE THREAD

**Issue by Tekl** [azettl/typemill.plugin.rss#1]
Hi and thanks a lot for making this plugin. Is it possible or will future releases make it possible to combine the feeds of all/some folders into a meta feed? I've a separate news and blog folder, but the user should also be able to follow both in one feed.

**Comment by azettl** [comment]
Hi @Tekl,

thanks a lot for your feedback! I just added the RSS feed for all folders. Please have a look.

Best Regards
Andreas

**Comment by Tekl** [comment]
Hi Andreas,

thanks for the quick implementation. Where do I find the combined feed? I don't have it on my homepage.

**Comment by Tekl** [comment]
The problem is solved after re-publishing the folders. The URL is `myhomepage.com/rss` and not `myhomepage.com/feed` as stated on in the plugin in directory on typemill.net.
