### ISSUE TITLE
Feeds are empty

### ISSUE THREAD

**Issue by Tekl** [azettl/typemill.plugin.rss#3]
When I access this feed <https://tekl.de/news/rss> it does not produce any output (HTTP status 200). Even the php_error.log does not give me a hint, what's going wrong. There isn't a basic XML skeleton, either.

**Comment by trendschau** [comment]
Just as an idea: Did you try to unpublish and/or publish a page? Because the rss feed is initially only created on those actions. I had the same problem when I installed it. It is also described on the plugin page. Does that fix the issue? https://plugins.typemill.net/rss

**Comment by Tekl** [comment]
Ah, thanks for the hint. That was the solution. 🤦
